---
parent: 'common/test_cases/origin_release.yml'
extensions:
  actions:
    - type: "script"
      title: "create directory for docker config"
      script: |-
        mkdir -p /tmp/.docker
        chmod a+rwx /tmp/.docker
    - type: "host_script"
      title: "transfer docker config to remote host"
      script: |-
        scp -F ./.config/origin-ci-tool/inventory/.ssh_config /var/lib/jenkins/.docker/config.json openshiftdevel:/tmp/.docker/
    - type: "script"
      title: "push the release"
      repository: "origin"
      script: |-
        export DOCKER_CONFIG=/tmp/.docker
        sudo chmod a+rw "${DOCKER_CONFIG}/config.json"
        export OS_PUSH_BASE_REGISTRY="docker.io/"
        OS_PUSH_TAG="$( git describe --abbrev=0 )"; export OS_PUSH_TAG
        hack/push-release.sh
        sudo rm -rf "${DOCKER_CONFIG}"